bin: improve script robustness and features

diff --git a/bin/last-git-backup b/bin/last-git-backup
--- a/bin/last-git-backup
+++ b/bin/last-git-backup
@@ -1,8 +1,7 @@
 #!/bin/bash
 # Check if there are any backups in the last 24h
-test -d ~/.vim-git-backups || exit 0
-cd ~/.vim-git-backups
-# if [ "$(git rev-list --count --since='1 day' HEAD)" -eq "0" ]; then
-#   echo '- NO BACKUPS in last 24h!!!!!!! ' 
-# fi
-
+test -d ~/.vim-git-backups || { echo 'vim-backups: dir-missing' && exit 0; }
+cd ~/.vim-git-backups || { echo 'vim-backups: cd-failed' && exit 1; }
+if [ "$(git rev-list --count --since='1 day' HEAD)" -eq 0 ]; then
+  echo  "vim-backups: NO BACKUPS in last 24h!! (last: $(git log -1 --pretty=format:'%h %ad %s'))"
+fi
diff --git a/bin/ps1-helper b/bin/ps1-helper
--- a/bin/ps1-helper
+++ b/bin/ps1-helper
@@ -4,7 +4,7 @@ set -euo pipefail
 
 (
   # Check if gcloud is installed
-  command -v gcloud >/dev/null 2>&1 || { echo >&2 "gcloud required but it's not installed.  Aborting."; exit 1; }
+  #command -v gcloud >/dev/null 2>&1 || { echo >&2 "gcloud required but it's not installed.  Aborting."; exit 1; }
 
   # Lock file path
   lockfile=~/.ps1-output-cache.lock
@@ -27,14 +27,22 @@ set -euo pipefail
       ~/bin/ps1-helper-local
     fi
     echo -n "$(date)"
-    echo -n " gcloud: $(gcloud -q config configurations list --filter=is_active:true | grep True | awk '{print $1}') $(gcloud config -q get-value project 2>/dev/null)"
+    command -v gcloud >/dev/null 2>&1 && (
+      gcloudcfg=$(gcloud -q config configurations list --filter=is_active:true | grep True | awk '{print $1}')
+      gcloudproject=$(gcloud config get-value project 2>/dev/null)
+      echo -n " gcloud:(${gcloudcfg:-default},${gcloudproject:-none})"
+    )
+
+    # crontab count:
+    echo -n " cjs:$(crontab -l 2>/dev/null | grep -cv '^#|^$')"
+
     # print current kubernetes context:
     # echo -n " k8s: $(kubectl config current-context 2>/dev/null)"
     # echo
     # Check for the existence of bash history backup script in cron jobs
-    # if ! crontab -l 2>&1 | grep -q 'backup-bash-history'; then
-    #     echo "Warning: bash history backup script is not in crontab"
-    # fi
+    if ! crontab -l 2>&1 | grep -q 'backup-bash-history'; then
+        echo "Warning: bash history backup script is not in crontab"
+    fi
   ) > ~/.ps1-output-cache_
   mv ~/.ps1-output-cache{_,}
 ) &
